name: build multiple platform image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.PINRY_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.PINRY_DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: bash docker/build_docker_multiple_platform.sh
