name: build multiple platform image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: linux/amd64,linux/arm64,linux/arm/v7
      - name: Login to DockerHub
        run: echo "${{ secrets.PINRY_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.PINRY_DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: bash docker/build_docker_multiple_platform.sh
